security:
    # Partie qui permet d'encrypter le mot de passe :
    encoders:

        App\Entity\Membre:

            algorithm: bcrypt # "Blowfish".
            cost: 14

    # Hierarchie :
    # "ROLE_ADMIN" a les droits de user + les siens.
    # "ROLE_SUPER_ADMIN" a les droits de "ROLE-ADMIN".
    # "ROLE_ALLOWED_TO_SWITCH" permet de changer de compte et de se faire passer pour quelqu'un d'autre.
    # Le "super admin" pourra accéder à un autre compte sans avoir son mot de passe. 
    role_hierarchy:
        ROLE_ADMIN: [ROLE_USER]
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TOSWITCH]

    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        main:
            entity:

                class: App\Entity\Membre
                property: email


    firewalls:
        dev:
            pattern: ^/((profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern: ^/
            provider: main
            anonymous: true
            form_login:
                login_path: login
                check_path: login
                default_target_path: /profil
            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800 # 1 semaine en secondes.
                path: / 
            logout: 
                path: /logout
                target: /

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, roles: ROLE_ADMIN }