# Nom de la page (index)
# Chemin vers la page (/)
# Controleur et methode a appeller
index:
    path: /
    controller: App\Controller\MainController::index

# Route et page fictive de connexion :
login:
  path: /login
  controller: App\Controller\MembreController::login

# Page de déconnexion fictive (gérée par Symfony) :
logout:
  path: /logout


